import Header from "@/components/Header";
import UserProvider from "@/components/UserProvider";
import "@/styles/globals.css";

const getCategories = async () => {
	const req = await fetch("http://localhost:3000/api/categories");
	return await req.json();
};

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	const categories = await getCategories();
	return (
		<html lang="en">
			<head>
				<title>Ecommerce</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</head>
			<body>
				<UserProvider>
					<Header categories={categories} />
					{children}
				</UserProvider>
			</body>
		</html>
	);
}

export const metadata = {
	title: "Ecommerce",
	description: "Ecommerce website made by Bartłomiej Tutak",
};
