import Head from "next/head";
import { useUser } from "@auth0/nextjs-auth0/client";
import SignIn from "@/components/SignIn";

export default function Home() {
	const { user, error, isLoading } = useUser();
	console.log(user);

	return (
		<>
			<Head>
				<title>Ecommerce</title>
				<meta name="description" content="Generated by create next app" />
				<meta name="viewport" content="width=device-width, initial-scale=1" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<main>
				<SignIn />
			</main>
		</>
	);
}
